### ISSUE TITLE
Not able to start service

### ISSUE THREAD

**Issue by AxelMKlein** [SebLisic/UpdateUbuntuCalendarIcon#1]
Hi,

I am not able to start the service:

> (base):~$ systemctl --user status update_calendar_icon.service
× update_calendar_icon.service - Update Calendar Icon to Current Date
     Loaded: loaded (/home/?/.local/share/systemd/user/update_calendar_icon.service; static)
     Active: failed (Result: exit-code) since Thu 2022-06-09 08:51:05 CEST; 6min ago
TriggeredBy: ● update_calendar_icon.timer
    Process: 158511 ExecStart=/home/?/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl update --other-date weekday --silent (code=exited, status=1/FAILURE)
   Main PID: 158511 (code=exited, status=1/FAILURE)
        CPU: 51.970s
Jun 09 08:50:17 systemd[52505]: Starting Update Calendar Icon to Current Date...
Jun 09 08:51:05  update_cal_icon.pl[158511]: Could not create '/home/?/.icons/Calendar-update-YaruNo such file or directory at /home/?/UpdateUbuntuCale>
Jun 09 08:51:05  systemd[52505]: update_calendar_icon.service: Main process exited, code=exited, status=1/FAILURE
Jun 09 08:51:05  systemd[52505]: update_calendar_icon.service: Failed with result 'exit-code'.
Jun 09 08:51:05  systemd[52505]: Failed to start Update Calendar Icon to Current Date.
Jun 09 08:51:05  systemd[52505]: update_calendar_icon.service: Triggering OnFailure= dependencies.
Jun 09 08:51:05  systemd[52505]: update_calendar_icon.service: Failed to enqueue OnFailure= job, ignoring: Unit mail-systemd-failure@update_calendar_icon.ser>
Jun 09 08:51:05 systemd[52505]: update_calendar_icon.service: Consumed 51.970s CPU time.

What can I do?
Thank you in advance.

**Comment by SebLisic** [comment]
There seems to be a problem with resolving your home dir. It shouldn't be "?". 

Can you run the following command in a terminal and provide the output?
`echo $HOME`

**Comment by AxelMKlein** [comment]
Sorry, I was deleting the name of the home directory in this log and replacing it with a question mark.

Therefore here comes the full log ( I don't know why the first three lines are stroke through here, in the original it is not):

> (base) axel@axelsxps:~$ echo $HOME
/home/axel
(base) axel@axelsxps:~$ 
(base) axel@axelsxps:~$ systemctl --user status update_calendar_icon.service
× update_calendar_icon.service - Update Calendar Icon to Current Date
     Loaded: loaded (/home/axel/.local/share/systemd/user/update_calendar_icon.service; static)
     Active: failed (Result: exit-code) since Sun 2022-06-12 03:02:52 CEST; 13h ago
TriggeredBy: ● update_calendar_icon.timer
    Process: 14092 ExecStart=/home/axel/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl update --other->
   Main PID: 14092 (code=exited, status=1/FAILURE)
        CPU: 26.630s
Jun 12 03:02:25 axelsxps systemd[2381]: Starting Update Calendar Icon to Current Date...
Jun 12 03:02:52 axelsxps update_cal_icon.pl[14092]: Could not create '/home/axel/.icons/Calendar-update>
Jun 12 03:02:52 axelsxps systemd[2381]: update_calendar_icon.service: Main process exited, code=exited,>
Jun 12 03:02:52 axelsxps systemd[2381]: update_calendar_icon.service: Failed with result 'exit-code'.
Jun 12 03:02:52 axelsxps systemd[2381]: Failed to start Update Calendar Icon to Current Date.
Jun 12 03:02:52 axelsxps systemd[2381]: update_calendar_icon.service: Triggering OnFailure= dependencie>
Jun 12 03:02:52 axelsxps systemd[2381]: update_calendar_icon.service: Failed to enqueue OnFailure= job,>
Jun 12 03:02:52 axelsxps systemd[2381]: update_calendar_icon.service: Consumed 26.630s CPU time.

**Comment by SebLisic** [comment]
Unfortunately I can't see the full log output. Would you run the command manually and give me the output?
`~/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl update`

**Comment by AxelMKlein** [comment]
The problem was that the directory ~/.icons did not exist. After I created it manually, the program works. :-)
Perhaps the program should detect the existance and create it in case of need.

Here is the log (Sorry again for the strike through, I don't know how to prevent it):

>(base) axel@axelsxps:~$ ~/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl update
Could not create '/home/axel/.icons/Calendar-update-YaruNo such file or directory at /home/axel/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl line 708.
(base) axel@axelsxps:~$ 
(base) axel@axelsxps:~$ 
(base) axel@axelsxps:~$ cd /home/axel/.icons
bash: cd: /home/axel/.icons: Datei oder Verzeichnis nicht gefunden
(base) axel@axelsxps:~$ mkdir /home/axel/.icons
(base) axel@axelsxps:~$ ~/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl update
Created symlink /home/axel/.icons/Calendar-update-Yaru/16x16/apps/calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/16x16/apps/gnome-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/16x16/apps/office-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/16x16/apps/org.gnome.Calendar.png
Created /home/axel/.icons/Calendar-update-Yaru/16x16/apps/calendar-app.png
Created /home/axel/.icons/Calendar-update-Yaru/16x16/apps/x-calendar-app.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/16x16@2x/apps/calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/16x16@2x/apps/gnome-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/16x16@2x/apps/office-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/16x16@2x/apps/org.gnome.Calendar.png
Created /home/axel/.icons/Calendar-update-Yaru/16x16@2x/apps/calendar-app.png
Created /home/axel/.icons/Calendar-update-Yaru/16x16@2x/apps/x-calendar-app.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/24x24/apps/calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/24x24/apps/gnome-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/24x24/apps/office-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/24x24/apps/org.gnome.Calendar.png
Created /home/axel/.icons/Calendar-update-Yaru/24x24/apps/calendar-app.png
Created /home/axel/.icons/Calendar-update-Yaru/24x24/apps/x-calendar-app.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/24x24@2x/apps/calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/24x24@2x/apps/gnome-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/24x24@2x/apps/office-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/24x24@2x/apps/org.gnome.Calendar.png
Created /home/axel/.icons/Calendar-update-Yaru/24x24@2x/apps/calendar-app.png
Created /home/axel/.icons/Calendar-update-Yaru/24x24@2x/apps/x-calendar-app.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/32x32/apps/calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/32x32/apps/gnome-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/32x32/apps/office-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/32x32/apps/org.gnome.Calendar.png
Created /home/axel/.icons/Calendar-update-Yaru/32x32/apps/calendar-app.png
Created /home/axel/.icons/Calendar-update-Yaru/32x32/apps/x-calendar-app.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/32x32@2x/apps/calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/32x32@2x/apps/gnome-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/32x32@2x/apps/office-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/32x32@2x/apps/org.gnome.Calendar.png
Created /home/axel/.icons/Calendar-update-Yaru/32x32@2x/apps/calendar-app.png
Created /home/axel/.icons/Calendar-update-Yaru/32x32@2x/apps/x-calendar-app.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/48x48/apps/calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/48x48/apps/gnome-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/48x48/apps/office-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/48x48/apps/org.gnome.Calendar.png
Created /home/axel/.icons/Calendar-update-Yaru/48x48/apps/calendar-app.png
Created /home/axel/.icons/Calendar-update-Yaru/48x48/apps/x-calendar-app.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/48x48@2x/apps/calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/48x48@2x/apps/gnome-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/48x48@2x/apps/office-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/48x48@2x/apps/org.gnome.Calendar.png
Created /home/axel/.icons/Calendar-update-Yaru/48x48@2x/apps/calendar-app.png
Created /home/axel/.icons/Calendar-update-Yaru/48x48@2x/apps/x-calendar-app.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/256x256/apps/calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/256x256/apps/gnome-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/256x256/apps/office-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/256x256/apps/org.gnome.Calendar.png
Created /home/axel/.icons/Calendar-update-Yaru/256x256/apps/calendar-app.png
Created /home/axel/.icons/Calendar-update-Yaru/256x256/apps/x-calendar-app.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/256x256@2x/apps/calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/256x256@2x/apps/gnome-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/256x256@2x/apps/office-calendar.png
Created symlink /home/axel/.icons/Calendar-update-Yaru/256x256@2x/apps/org.gnome.Calendar.png
Created /home/axel/.icons/Calendar-update-Yaru/256x256@2x/apps/calendar-app.png
Created /home/axel/.icons/Calendar-update-Yaru/256x256@2x/apps/x-calendar-app.png
(base) axel@axelsxps:~$

**Comment by SebLisic** [comment]
Thanks for input! I updated the program to now create the .icons dir if missing.
