### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by foxrus** [SebLisic/UpdateUbuntuCalendarIcon#2]
`~/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl install-timer --now

Creating user Systemd files
Created /home/linuxcool/.local/share/systemd/user/update_calendar_icon.service
Created /home/linuxcool/.local/share/systemd/user/update_calendar_icon.timer
Job for update_calendar_icon.service failed because the control process exited with error code.
See "systemctl --user status update_calendar_icon.service" and "journalctl --user -xeu update_calendar_icon.service" for details.
Failed to run '/usr/bin/systemctl start --user update_calendar_icon.service': 256 at /home/linuxcool/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl line 406.
`
`× update_calendar_icon.service - Update Calendar Icon to Current Date
     Loaded: loaded (/home/linuxcool/.local/share/systemd/user/update_calendar_icon.service; static)
     Active: failed (Result: exit-code) since Fri 2022-06-10 09:04:04 EEST; 49s ago
TriggeredBy: ● update_calendar_icon.timer
    Process: 69491 ExecStart=/home/linuxcool/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl update --other-date weekday --silent (code=exit>
   Main PID: 69491 (code=exited, status=1/FAILURE)
        CPU: 19.720s

июн 10 09:03:45 fox-pc systemd[1223]: Starting Update Calendar Icon to Current Date...
июн 10 09:03:45 fox-pc update_cal_icon.pl[69491]: Use of uninitialized value in substitution (s///) at /home/linuxcool/UpdateUbuntuCalendarI>
июн 10 09:03:45 fox-pc update_cal_icon.pl[69491]: Use of uninitialized value $accentColor in substitution (s///) at /home/linuxcool/UpdateUb>
июн 10 09:04:04 fox-pc update_cal_icon.pl[69491]: Could not create '/home/linuxcool/.icons/Calendar-update-Colloid-darkNo such file or direc>
июн 10 09:04:04 fox-pc systemd[1223]: update_calendar_icon.service: Main process exited, code=exited, status=1/FAILURE
июн 10 09:04:04 fox-pc systemd[1223]: update_calendar_icon.service: Failed with result 'exit-code'.
июн 10 09:04:04 fox-pc systemd[1223]: Failed to start Update Calendar Icon to Current Date.
июн 10 09:04:04 fox-pc systemd[1223]: update_calendar_icon.service: Triggering OnFailure= dependencies.
июн 10 09:04:04 fox-pc systemd[1223]: update_calendar_icon.service: Failed to enqueue OnFailure= job, ignoring: Unit mail-systemd-failure@up>
июн 10 09:04:04 fox-pc systemd[1223]: update_calendar_icon.service: Consumed 19.720s CPU time.
`

**Comment by SebLisic** [comment]
It looks like you are not using an Ubuntu icon theme. I am working on adding support for this now. Would you provide a link to where you got the "Colloid-dark" theme so I can test it?

**Comment by foxrus** [comment]
https://www.gnome-look.org/p/1661983/

**Comment by foxrus** [comment]
When I apply the yaru icons theme, errors also appear
`linuxcool@fox-pc:~/src/UpdateUbuntuCalendarIcon$ ~/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl install-timer --now

Creating user Systemd files
Created /home/linuxcool/.local/share/systemd/user/update_calendar_icon.service
Created /home/linuxcool/.local/share/systemd/user/update_calendar_icon.timer
Job for update_calendar_icon.service failed because the control process exited with error code.
See "systemctl --user status update_calendar_icon.service" and "journalctl --user -xeu update_calendar_icon.service" for details.
Failed to run '/usr/bin/systemctl start --user update_calendar_icon.service': 256 at /home/linuxcool/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl line 406.
`

**Comment by SebLisic** [comment]
Would you provide the log output?
`journalctl --user -xeu update_calendar_icon.service`

**Comment by SebLisic** [comment]
I am guessing the .icon dir was missing. I updated the app to fix this. You can update with the following command:
`cd ~/src/UpdateUbuntuCalendarIcon`
`git pull`
`make uninstall`
`make install`
`~/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl install-timer --now`
`
