### ISSUE TITLE
Not start.

### ISSUE THREAD

**Issue by Deltahh** [SebLisic/UpdateUbuntuCalendarIcon#3]
**systemctl --user start update_calendar_icon.service**

Job for update_calendar_icon.service failed because the control process exited with error code.
See "systemctl --user status update_calendar_icon.service" and "journalctl --user -xeu update_calendar_icon.service" for details.

------------------------------------

**~/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl install-timer --now**

Creating user Systemd files
Created /home/daniel/.local/share/systemd/user/update_calendar_icon.service
Created /home/daniel/.local/share/systemd/user/update_calendar_icon.timer
Job for update_calendar_icon.service failed because the control process exited with error code.
See "systemctl --user status update_calendar_icon.service" and "journalctl --user -xeu update_calendar_icon.service" for details.
Failed to run '/usr/bin/systemctl start --user update_calendar_icon.service': 256 at /home/daniel/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl line 406.

------------------------------------

**systemctl --user status update_calendar_icon.service**

× update_calendar_icon.service - Update Calendar Icon to Current Date
     Loaded: loaded (/home/daniel/.local/share/systemd/user/update_calendar_ico>
     Active: failed (Result: exit-code) since Fri 2022-06-10 21:08:06 -03; 33s >
TriggeredBy: ● update_calendar_icon.timer
    Process: 31682 ExecStart=/home/daniel/UpdateUbuntuCalendarIcon/bin/update_c>
   Main PID: 31682 (code=exited, status=1/FAILURE)
        CPU: 12.048s

jun 10 21:07:55 daniel-H370M-DS3H systemd[2949]: Starting Update Calendar Icon >
jun 10 21:08:06 daniel-H370M-DS3H update_cal_icon.pl[31682]: Could not create '>
jun 10 21:08:06 daniel-H370M-DS3H systemd[2949]: update_calendar_icon.service: >
jun 10 21:08:06 daniel-H370M-DS3H systemd[2949]: update_calendar_icon.service: >
jun 10 21:08:06 daniel-H370M-DS3H systemd[2949]: Failed to start Update Calenda>
jun 10 21:08:06 daniel-H370M-DS3H systemd[2949]: update_calendar_icon.service: >
jun 10 21:08:06 daniel-H370M-DS3H systemd[2949]: update_calendar_icon.service: >
jun 10 21:08:06 daniel-H370M-DS3H systemd[2949]: update_calendar_icon.service: >

--------------------------------------

**journalctl --user -xeu update_calendar_icon.service**

The process' exit code is 'exited' and its exit status is 1.
jun 10 21:08:06 daniel-H370M-DS3H systemd[2949]: update_calendar_icon.service: >
Subject: Unit failed
Defined-By: systemd
Support: http://www.ubuntu.com/support

The unit UNIT has entered the 'failed' state with result 'exit-code'.
jun 10 21:08:06 daniel-H370M-DS3H systemd[2949]: Failed to start Update Calenda>
Subject: A start job for unit UNIT has failed
Defined-By: systemd
Support: http://www.ubuntu.com/support

A start job for unit UNIT has finished with a failure.
The job identifier is 749 and the job result is failed.
jun 10 21:08:06 daniel-H370M-DS3H systemd[2949]: update_calendar_icon.service: >
jun 10 21:08:06 daniel-H370M-DS3H systemd[2949]: update_calendar_icon.service: >
jun 10 21:08:06 daniel-H370M-DS3H systemd[2949]: update_calendar_icon.service: >
Subject: Resources consumed by unit runtime
Defined-By: systemd
Support: http://www.ubuntu.com/support

The unit UNIT completed and consumed the indicated resources.

**Comment by SebLisic** [comment]
Some of the log is being cut off. Would you try updating the icon theme manually by running this command and providing the output?

`~/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl update`

**Comment by SebLisic** [comment]
I am guessing the .icon dir was missing. I updated the app to fix this. You can update with the following command:
`
cd ~/src/UpdateUbuntuCalendarIcon
$ git pull
$ make uninstall
$ make install
$ ~/UpdateUbuntuCalendarIcon/bin/update_cal_icon.pl install-timer --now
`
